version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: licitabrasil-prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - licitabrasil-network

  alertmanager:
    image: prom/alertmanager:latest
    container_name: licitabrasil-alertmanager
    restart: unless-stopped
    volumes:
      - ./monitoring/alertmanager:/etc/alertmanager
      - alertmanager_data:/alertmanager
    ports:
      - "9093:9093"
    networks:
      - licitabrasil-network

  grafana:
    image: grafana/grafana:latest
    container_name: licitabrasil-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=CHANGE_ME_GRAFANA_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=monitoring.licitabrasilweb.com.br
      - GF_SERVER_ROOT_URL=https://monitoring.licitabrasilweb.com.br/
    volumes:
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - licitabrasil-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: licitabrasil-node-exporter
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)(255058|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
    networks:
      - licitabrasil-network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: licitabrasil-postgres-exporter
    restart: unless-stopped
    env_file:
      - ./monitoring/exporters/postgres-exporter.env
    ports:
      - "9187:9187"
    networks:
      - licitabrasil-network

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: licitabrasil-redis-exporter
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis://redis:6379
      - REDIS_PASSWORD=CHANGE_ME_REDIS_PASSWORD
    ports:
      - "9121:9121"
    networks:
      - licitabrasil-network

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: licitabrasil-blackbox-exporter
    restart: unless-stopped
    ports:
      - "9115:9115"
    networks:
      - licitabrasil-network

volumes:
  prometheus_data:
  alertmanager_data:
  grafana_data:

networks:
  licitabrasil-network:
    external: true
    name: toor_licitabrasil-network
